### ISSUE TITLE
/Pages/SPINS.html - Hostile Act / Hostile intention - Speed should not be a criteria

### ISSUE THREAD

**Issue by jkhoel** [132nd-vWing/ATRM_Brief#1]
I would suggest not having criteria along the lines of "Hot toward friendlies, with a groundspeed of 500kts or higher" as this is not a definite description as something only a hostile would do.

It would in my opinion be better to write something along the lines of "moving tactically towards friendlies" as this is something that AWACS or Pilots monitoring the contact should be able to recognize and assess.

**Comment by 132ndNeck** [comment]
Adjusted now:
https://132nd-vwing.github.io/ATRM_Brief/Pages/SPINS.html
