### ISSUE TITLE
add a webhook channel for this repo in discord

### ISSUE THREAD

**Issue by steven-omaha** [132nd-vWing/ATRM_Brief#15]
Low priority.

Can we get a webhook channel like `#atrm_github` or `#opuf_brief_github` for this repo as well?

Some of the stuff here gets copied into kneeboards. Would be nice to see which stuff gets updated, so that we know when we need to update our kneeboard.

**Comment by 132ndNeck** [comment]
Created a webhook channel now.
Closing this issue
