### ISSUE TITLE
Tankers encroach range 9 

### ISSUE THREAD

**Issue by 132Ashilta** [132nd-vWing/ATRM_Brief#16]
It looks and feels like two of the tankers in the ATRM mission encroach on the western edge of Range 9. We subsequently have a big chunk of airspace on the western side of the range - maybe a 10nm wide corridor - that's impossible to use. Can we consider either:
* Taking a chunk out of the range and giving it to the tankers
* Moving them

**Comment by 132ndNeck** [comment]
Tankers are placed there on purpose to facilitate short distance to tankers for various trainings.

However, we will  deactive both tanker tracks by default, and make them active via F10 as required as the rest of the tanker tracks.

Closing this issue, as it will be handled on the ATRM Issue tracker as Issue 15 (REQ HELP: Tanker and AWACS orbits)
