### ISSUE TITLE
Master Freqs: TCN issues on Recovery Tanker/AR202

### ISSUE THREAD

**Issue by martinco** [132nd-vWing/ATRM_Brief#21]
Recovery Tanker is 64Y on 2 page summary - but 48Y in mission (as per: https://github.com/132nd-vWing/ATRM/blob/9aeb20c120613915019314dec9049778f2bfee25/l10n/DEFAULT/ATRM_Airboss.lua#L8)

AR202 TCN is 48X (correct) in 2 page summary, but not in Frequencies sheet (says 48Y)

**Comment by 132nd-Entropy** [comment]
@132ndNeck happy to fix this, just want to coordinate with you which freq should be what since 48Y is apparently used twice

**Comment by 132nd-Entropy** [comment]
fixed, thanks for reporting, good catch
