### ISSUE TITLE
R15 frequency

### ISSUE THREAD

**Issue by 132nd-etcher** [132nd-vWing/ATRM_Brief#29]
R15 has no assigned frequency as per https://132nd-vwing.github.io/ATRM_Brief/Files/ATRM%20freqs%20overview.pdf

**Comment by 132nd-Entropy** [comment]
friendly bump

**Comment by 132ndNeck** [comment]
Fixed.

**Comment by YouthfulIndiscretion** [comment]
@132ndNeck @132nd-Entropy Thank you!

**Comment by 132nd-etcher** [comment]
@132ndNeck @132nd-Entropy Thank you!
