### ISSUE TITLE
F14 (SPECTRE and KNIGHT) laser code ranges

### ISSUE THREAD

**Issue by evilivan** [132nd-vWing/ATRM_Brief#3]
SPECTRE and KNIGHT currently have two problems with laser codes:

1) They both have the same ranges (1455-1458)
2) Those ranges don't work in the F14; the F14 has the following restrictions for laser code ranges:
Digit 1: must be 1
Digit 2: can be 5, 6, or 7
Digit 3: can be 1-8
Digit 4: can be 1-8

Thanks for fixing :-)

**Comment by 132ndNeck** [comment]
Thanks for reporting.
Updated briefing now with corrected lasercodes for all flights.
