### ISSUE TITLE
Presets on Mi8

### ISSUE THREAD

**Issue by Looney1976** [132nd-vWing/ATRM_Brief#37]
Can we get the Mi8s to have the following presets:

  | R-863
-- | --
1 | 126.100
2 | 126.200
3 | 127.100
4 | 237.000
5 | 119.200
6 | 119.400
7 | 121.100
8 | 121.200
9 | 229.000
10 | 227.500
11 | 228.500
12 | 228.250
13 | 127.500
14 | 225.750
15 | 235.750
16 | 233.250
17 | 242.250
18 | 231.250
19 | 309.000
20 | 136.250

  | R-828
-- | --
1 | 35.60
2 | 32.90
3 | 48.50
4 | 33.80
5 | 36.30
6 | 37.80
7 | 38.20
8 | 33.50
9 | 38.50
10 | 34.25

If I can help, please let me know.

**Comment by 132nd-Entropy** [comment]
Hi @Looney1976 at this point I think we need to work together as there is simply too many tasks for one person. May I request you download the very latest ATRM from here, 

https://ci.appveyor.com/project/132nd-VirtualWing/atrm

make sure nobody is working on it at the same time (best ask in MSN making channel) and edit the presets for all Mi8s. Once finished send to me via discord and I feed it into the builder to make a new version

**Comment by Looney1976** [comment]
[Mi-8 presets ATRM PG.pdf](https://github.com/132nd-vWing/ATRM_Brief/files/5579535/Mi-8.presets.ATRM.PG.pdf)
MI-8 presets set in mission and attached file made for briefing page, frequencies, please add.
