### ISSUE TITLE
Add instructions for Range-14 "preset CAS Scenarios"

### ISSUE THREAD

**Issue by IAFAssafB** [132nd-vWing/ATRM_Brief#40]
I'd like to add the following text to the briefing, describing the new scenarios and how they should be used but can't handle the editor too well hence would appreciate if anyone more competent could support:

> CAS pre-set random scenarios, Range-14:
> The random pre-set CAS scenarios are aimed to provide the JTAC with practicing a rapid preparation of his situation updates based on details provided by a simulated Ground Force Commander.
> 
> How-To-Use:
> 1) Once in the mission, first take any slot of a USA airframe and then switch to TACTICAL COMMANDER or JTAC (The purpose of this is to allow receiving of messages generated only for specific users. **This step is essential!**
> 2) In the F10 menu, select ACTIVATE RANGE-14 PRESET CAS SCENARIO RANDOMLY. This would display the GFC-briefing to you providing you with the situation , priorities, restrictions and other scenario-specific information. It is highly advised to screenshot this screen so that the brief can be read later on as needed.
> 3)  The briefing relates to this map: 
> https://cloud.132virtualwing.org/s/RdHNqBNkNNgwWiP
> 4) After a few minutes, The "regular" JTAC unit of the range will deactivate and only the scenario-specific JTAC would be available (The GFC brief also states the LATLONG of your JTAC position for this scenario).
>5) Similarly, the scenarios can also be selected specifically rather than randomly by choosing "CAS Preset scenario 1", CAS Preset scenario2" etc.

**Comment by 132nd-Entropy** [comment]
see here, this should be added to the breifing

https://github.com/132nd-vWing/ATRM/issues/116
