### ISSUE TITLE
two more VFR routes around OMAM

### ISSUE THREAD

**Issue by steven-omaha** [132nd-vWing/ATRM_Brief#6]
When RWY31 is in use, and the 617th recovers from SW, we need to make a pretty long detour for LUGAL 3, entering at VILLAGE.  I would like to propose a new route for both directions, using a new navpoint HIGHWAY. This would establish the new departues MANSA 4 and LUGAL 4, thereby creating more flexibility and shorter ingress when the navigation target is in the direction of the take-off.

![CF map](https://cdn.discordapp.com/attachments/605831249587732497/672524802594177025/MANSA4_LUGAL4.png)

![DCS map](https://cdn.discordapp.com/attachments/605831249587732497/672524802757754927/highway.png)

![HIGHWAY](https://cdn.discordapp.com/attachments/605831249587732497/672524802996699164/highway_air.png)

**Comment by steven-omaha** [comment]
HIGHWAY is located N24 12.806 E054 24.900

**Comment by jkhoel** [comment]
I get the MANSA-4, but what is labeled LUGAL-4 on the first picture above does not make any sense to me. You are not recovering, but ending up at HIGHWAY.

The recovery matching MANSA-4 should be named MALIK-4 for consistency, and be the exact reciprocal. So a MANSA-4 Recovery would be Just overfly HIGHWAY and then join the pattern or whatever else you want to do/is directed to do.

**Comment by steven-omaha** [comment]
Totally correct, my mistake. When I talk about recovery, I ment MALIK-4 and LAMANE-4. These would then correspond to departures MANSA-4 and LUGAL-4.

**Comment by 132ndNeck** [comment]
Copy, will look into this the coming weekend and add a couple more points/routes as requested.

**Comment by 132nd-Entropy** [comment]
shall this be closed or is this still something that should be done?

**Comment by 132ndNeck** [comment]
I suggets we close it. It was WIP while I worked with the VFR navpoints, but is now handled by the "ATC Task force"
